-- 个人中心：users 表增加学校、专业、年级、年龄、性别、题型偏好、难度偏好、题目数量
ALTER TABLE users ADD COLUMN IF NOT EXISTS school VARCHAR(200);
ALTER TABLE users ADD COLUMN IF NOT EXISTS major VARCHAR(200);
ALTER TABLE users ADD COLUMN IF NOT EXISTS grade VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS age INTEGER;
ALTER TABLE users ADD COLUMN IF NOT EXISTS gender VARCHAR(20);
ALTER TABLE users ADD COLUMN IF NOT EXISTS question_type_preference VARCHAR(500);
ALTER TABLE users ADD COLUMN IF NOT EXISTS difficulty_preference VARCHAR(50);
ALTER TABLE users ADD COLUMN IF NOT EXISTS question_count INTEGER;
